services:

  app:
    build: .
    volumes:
      - ./:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: geheim
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'   
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./.devcontainer/servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always          
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: geheim
    volumes:                 
      - pg-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgadmin-data:
  pg-data: